# Generated by Django 5.2.6 on 2025-09-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
